#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 19 09:41:29 2022

@author: pantale
"""

from pathlib import Path
import fnmatch

def formDoc(label, brief, ret, warn, doc):
    return label, [brief, ret, warn, doc]

def findFiles(path, pattern):
    lst = []
    for file in Path(path).rglob(pattern):
        lst.append(file)
    return lst

def readFile(file):
    with open(file, 'r') as myfile:
        data = myfile.read().splitlines()
    return data

def writeFile(file, data):
    with open(file, 'w') as myfile:
        for line in data:
            myfile.write(line + '\n')

def after(s, delim):
    return s.partition(delim)[2]

def cleanTex(targetFile):
    data = readFile(targetFile)
    out = []
    write = True
    for line in data:
        if '%@DOC:' in line:
            out.append(line.replace('  ',' '))
            write = False
        if (write):
            out.append(line)
        if '%@END' in line:
            out.append(line)
            write = True
    return out

# Start of the main application
print("cleanDocumentation")
print("(c) by Olivier Pantalé 2022")

sources = "../Sources"
target = "."

targetFiles = findFiles(target, "*.tex")

for targetFile in targetFiles:
    cl = cleanTex(targetFile)
    writeFile(targetFile, cl)
    