#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 19 09:41:29 2022

@author: pantale
"""

from pathlib import Path
import fnmatch

def formDoc(label, brief, ret, arg, warn, smod, doc):
    return label, [brief, ret, arg, warn, smod, doc]

def findFiles(path, pattern):
    lst = []
    for file in Path(path).rglob(pattern):
        lst.append(file)
    return lst

def readFile(file):
    with open(file, 'r') as myfile:
        data = myfile.read().splitlines()
    return data

def writeFile(file, data):
    with open(file, 'w') as myfile:
        for line in data:
            myfile.write(line + '\n')
            
def extractDoc(files):
    documentation = []
    doc = False
    for file in files:
        data = readFile(file)
        for line in data:
            if line.startswith('@LABEL:'):
                line = line.replace('  ',' ')
                doc = True
            if doc:
                documentation.append(line)                 
            if line.startswith('@END'):      
                doc = False
    return documentation

def after(s, delim):
    return s.partition(delim)[2]

def before(s, delim):
    return s.partition(delim)[0]

def texify(str, et=False):
    str = str.replace('~','$\sim$')
    str = str.replace('()','(~)')
    if et:
        str = str.replace('&','\&')    
        str = str.replace('*','$\star$')
    return str

def returnDoc(data):
    Docs = {}
    doc = []
    label = ''
    arg = []
    desc = ''
    ret = ''
    warn = ''
    smod = False
    go = False
    for line in data:
        if (go):
            ok = False
            if '@SHORT' in line:
                desc = after(line,'@SHORT:')
                ok = True
            if '@ARG' in line:
                arg.append(after(line,'@ARG:'))
                ok = True     
            if '@RETURN' in line:
                ret = after(line,'@RETURN:')
                ok = True                
            if '@WARNING' in line:
                warn = after(line,'@WARNING:')
                ok = True    
            if '@SMOD' in line:
                smod = True
                ok = True     
            if (ok == False):
                if not '@END' in line:
                    doc.append(line)
        if '@LABEL' in line:
            label = after(line,'@LABEL:')
            go = True
        if '@END' in line:
            go = False
            k, l = formDoc(label, desc, ret, arg, warn, smod, doc)
            Docs[k] = l
            doc = []
            label = ''
            arg = []
            desc = ''
            ret = ''
            warn = ''
            smod = False
    return Docs

def getTexKeys(targetFile):
    data = readFile(targetFile)
    out = []
    for line in data:
        if '%@DOC:' in line:
            out.append(after(line.replace('  ',' '),'%@DOC:'))
    return out

def cleanTex(targetFile):
    data = readFile(targetFile)
    out = []
    write = True
    for line in data:
        if '%@DOC:' in line:
            out.append(line.replace('  ',' '))
            write = False
        if (write):
            out.append(line)
        if '%@END' in line:
            out.append(line)
            write = True
    return out

def addDocToTex(data):
    out = []
    write = True
    for line in data:
        if '%@DOC:' in line:
            out.append(line)
            key = after(line,'%@DOC:')
            out = writeTex(out, key)
            write = False
        if (write):
            out.append(line)
        if '%@END' in line:
            out.append(line)
            write = True
    return out

def writeTex(out, key):
    # Writes the warning
    out.append("%Warning :\n%This area is an automatic documentation generated from the DynELA source code.\n%Do not change anything in this latex file between this position and the @END keyword.")
    
    # Writes the header
    ln = "\\textcolor{purple}{\\textbf{" + texify(key,True) + "}}\\label{" + key + "}"
    
    # Writes the cross index
    if '::' in key :
        ln2 = key.replace('::','!')
        ln += '\\index[DL]{'+texify(ln2,True)+'}'   
        
    # If key exists, write the corresponding documentation
    if key in docs:
        dc = docs[key]

        # Writes the short documentation if exists
        if dc[0]!='' :
            ln += '\\\\\n' + dc[0]
 
        # Writes the return
        if dc[1]!='' :
            ln += ("\\\\ \\hspace*{10mm}$\\hookrightarrow$ "+dc[1])
        out.append(ln)
        out.append('')
            
        # Writes the Warning
        if dc[3]!='' :
            out.append('\\hspace*{10mm}\\textcolor{red}{\\textbf{Warning :} '+dc[3]+'}')
            out.append('')

        # Writes the self modification
        if dc[4]==True:
            out.append('\\hspace*{10mm}\\textcolor{red}{\\textbf{Warning :}} After the call to this method, the object is modified.')
            out.append('')

        # Scan args
        if (dc[2] != []):
            ln = '\\begin{tcolorbox}[width=\\textwidth,myArgs,tabularx={ll|R}]\n'
            #ln = '\\begin{tcolorbox}[width=\\textwidth,myArgs,tabularx={ll|R},title=Arguments of '+before(texify(key,True),'(')+']\n'
            for arg in dc[2]:
                ln += arg 
                if arg != dc[2][-1]:
                    ln += '\\\\'
                ln += '\n'
            ln += '\\end{tcolorbox}\n'
            out.append(ln)            

        # Writes the documentation
        for ln in dc[-1]:
            out.append(ln)
            
    # Else, writes that the documentation have to be written
    else:
        ln += " : \\textcolor{red}{\\textbf{No documentation defined in source files.}}"
        out.append(ln)
        out.append('')
    return out

# Start of the main application
print("updateDocumentation")
print("(c) by Olivier Pantalé 2022")

sources = "../Sources"
target = "."

sourceFiles = findFiles(sources, "*.[Ch]")
targetFiles = findFiles(target, "*.tex")

docs = returnDoc(extractDoc(sourceFiles))

for targetFile in targetFiles:
    cl = cleanTex(targetFile)
    tex = addDocToTex(cl)
    writeFile(targetFile, tex)
    